//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KCVDB.KanColleViewerPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KCVDB.KanColleViewerPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   艦これ検証部 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (ﾟдﾟ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonLabelSwitchChinese {
            get {
                return ResourceManager.GetString("ButtonLabelSwitchChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2016 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyrightYear {
            get {
                return ResourceManager.GetString("CopyrightYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信履歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HistoryListTitle {
            get {
                return ResourceManager.GetString("HistoryListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://kcvdb.jp/KanColleViewer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KcvdbPluginWebUrl {
            get {
                return ResourceManager.GetString("KcvdbPluginWebUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   転送量 / 時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitleDataAmountPerHour {
            get {
                return ResourceManager.GetString("MetricsTitleDataAmountPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信失敗回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitleFailureCount {
            get {
                return ResourceManager.GetString("MetricsTitleFailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信済みAPI数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitleNumApisTransferred {
            get {
                return ResourceManager.GetString("MetricsTitleNumApisTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッションID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitleSessionId {
            get {
                return ResourceManager.GetString("MetricsTitleSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信開始時刻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitleStartedAt {
            get {
                return ResourceManager.GetString("MetricsTitleStartedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信成功回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitleSuccessCount {
            get {
                return ResourceManager.GetString("MetricsTitleSuccessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総転送量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MetricsTitleTotalDataAmountSent {
            get {
                return ResourceManager.GetString("MetricsTitleTotalDataAmountSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KCVDB データ送信プラグインの更新があります。
        ///最新版の取得ページを開きますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewerVersionAvailableMessage {
            get {
                return ResourceManager.GetString("NewerVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【緊急更新】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewerVersionAvailableMessageEmergencyPrefix {
            get {
                return ResourceManager.GetString("NewerVersionAvailableMessageEmergencyPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KCVDB データ送信プラグイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信エラー情報などをKCVDBに送信する（次回起動時反映） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingCaptionEnableSendingTelemetry {
            get {
                return ResourceManager.GetString("SettingCaptionEnableSendingTelemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KCVDB に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolPluginName {
            get {
                return ResourceManager.GetString("ToolPluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://kcvdb.jp/plugin/version.php に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionInfoUrl {
            get {
                return ResourceManager.GetString("VersionInfoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version {0}.{1}.{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VersionStringTemplate {
            get {
                return ResourceManager.GetString("VersionStringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://kcvdb.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebUrl {
            get {
                return ResourceManager.GetString("WebUrl", resourceCulture);
            }
        }
    }
}
